site:
  title: NT-REST Docs
  url: https://docs.nt-rest.com/
content:
  sources: 
  - url: ./
asciidoc:
  attributes:
    experimental: true
    kroki-fetch-diagram: true
    kroki-default-format@: svg
  extensions:
    - asciidoctor-kroki
    #- ./lib/swagger-ui-block-macro.js
    #- ./lib/tabs-block.js
ui:
  bundle:
    url: ./../nt-rest.github.ui/build/ui-bundle.zip
    snapshot: true
  output_dir: static
  supplemental_files: ./supplemental_files
